name: 'olist'
version: '1.0.0'
profile: 'olist'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

on-run-end:
  - "{% if flags.WHICH in ['run', 'build'] %}{{ build_agents_schema() }}{% endif %}"

models:
  olist:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table
      +tags: ['agent']
