name: 'olist'
version: '1.0.0'
profile: 'olist'

require-dbt-version: [">=2.0.0-preview", "<3.0.0"]

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  olist:
    staging:
      +materialized: view
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
